name: Reusable Authorize Commit Signing
on:
  workflow_call:
    inputs:
      repository-name:
        required: true
        type: string

jobs:
  auth-commit-sig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          # Critical: check out the head commit on the branch. By default,
          # actions/checkout will check out a merge commit built for the pull
          # request and signed by Github itself. Using the pull-request HEAD
          # allows the action to check the latest commit on the pull request,
          # which must be signed by an authorized user before it can be merged.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout Allowlist repository
        uses: actions/checkout@v3
        with:
          # Path to allowlist repository in the format (owner/repo_name).
          # If it is the same repository as above, can skip this step.
          repository: "cloudpki/bipl"
          # SSH Key for private repositories. If repo is public, can omit.
          # See https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys.
          # The key should be stored as an actions secret or fetched from a secrets manager.
          # See https://docs.github.com/en/actions/security-guides/encrypted-secrets.
          ssh-key: ${{ secrets.ALLOWLIST_REPO_SSH_PRIV_KEY }}
          # Relative path under $GITHUB_WORKSPACE to place the repository.
          # NOTE: the repo_name will not be cloned as a folder. Only the files will
          # be checked out at this path.
          path: "allow_list"
      - name: Authorize with Beyond Identity
        id: signature-verification
        uses: gobeyondidentity/auth-commit-sig@v1.0.0-rc10
        with:
          # API Token to call Beyond Identity cloud.
          # The token should be stored as an actions secret or fetched from a secrets manager.
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets.
          api_token: ${{ secrets.BYNDID_KEY_MGMT_API_TOKEN }}
          # Repository which the signature verification action is performed on.
          # This is also used to match against repositories listed on the allowlist.
          #repository: "gobeyondidentity/auth-commit-sig"
          #repository: ${{ inputs.repository-name }}
          repository: "cloudpki/bipl"
          allowlist_config_file_path: "./allow_list/allowlist_example.yml"
        # Echo outcome JSON to standard out.
        # Outcome can be used in other steps as ${{ steps.signature-verification.outputs.outcome }}.
      - name: Print outcome
        run: |
          echo '${{ steps.signature-verification.outputs.outcome }}'
    # Output of job. Can be accessed in other jobs as ${{ needs.auth-commit-sig.outputs.outcome }}.
    outputs:
      outcome: ${{ steps.signature-verification.outputs.outcome }}
